### ISSUE TITLE
Cambios CVU

### ISSUE THREAD

**Issue by GustavoArreola** [wlmb/CVU#70]
Estimados y estimadas:

Como algunos habrán podido notar, en estas últimas semanas se han realizado cambios en la plataforma del CVU. Como les comenté en la reunión que tuvimos en CONACYT, esta primera etapa es de cambios pequeños, pero necesarios en la plataforma. Entre los cambios más importantes se encuentran:

 1) Los identificadores de autor ahora están únicamente en la sección de datos generales.
 2) Se quitó la obligatoriedad de "Resumen" para los capítulos de libro.
 3) Cambios de Tooltips (la información que aparece al pasar el cursos sobre los signos de interrogación).
 4) Mejora de catálogos de idiomas de traducción, especialmente la adición de lenguas indígenas.
 5) Se eliminó el campo de "Dictamen" de la sección Evaluaciones.
 6) Se atendieron las incidencias que no permitían guardar información.

Seguimos trabajando en otros cambios, los cuales esperamos puedan verse reflejados en las próximas semanas:

 1) Un nuevo formato de salida en PDF del CVU.
 2) Eliminar de la interfaz campos innecesarios de "Colaboradores" (Ya la mayoría no son obligatorios).
 3) Eliminar el campo "País" de publicación de artículos.

No omito mencionar que, como ya se comentó en el foro, que algunos de ustedes, especialmente el Dr. Luis Mochán, están trabajando en conjunto con el área de sistemas para permitir el uso de un CVU "libre ma non troppo"

Saludos cordiales

Gustavo Arreola

**Comment by wlmb** [comment]
Estimado Gustavo, Gracias por la lista de avances, pero como te decía directamente en la lista, sería conveniente empatar cada avance o solución en el registro del asunto correspondiente, en lugar de abrir un nuevo *asunto* para listar todos los avances realizados a la fecha. La idea de github es contar con una herrarmienta para poder dar seguimiento puntual a cada asunto hasta su solución, de uno en uno. Por tal motivo, por corresponder a varios asuntos a la vez, voy a cerrar éste.
Saludos,
Luis

**Comment by CVU2017** [comment]
Estimado Gustavo,

El sistema de CVU es un sistema de DATOS más importantes de la comunidad científica mexicana. Por eso hay que cuidarlo de manera especial y a largo plazo.
Por eso les recomiendo a que revisen y adopten el Modelo de Madurez de Datos ( Data Maturity Model DMM) que, al ser implementado, nos puede ayudar a todos  ahorrar muchas frustraciones y costos.

Saludos Hanna Oktaba

Enviado desde mi iPhone

**Comment by CVU2017** [comment]
Estimada Dra. Hanna Oktaba.

Muchas gracias, vamos a revisar el Modelo.

Saludos

Gustavo

De: Cvu [mailto:cvu-bounces@em.fis.unam.mx] En nombre de CVU2017
Enviado el: viernes, 4 de mayo de 2018 07:06 p. m.
Para: wlmb/CVU <CVU@noreply.github.com>
CC: CVU2017 <cvu@em.fis.unam.mx>; Your activity <your_activity@noreply.github.com>
Asunto: Re: [Cvu] [wlmb/CVU] Cambios CVU (#70)

Estimado Gustavo,

El sistema de CVU es un sistema de DATOS más importantes de la comunidad científica mexicana. Por eso hay que cuidarlo de manera especial y a largo plazo.
Por eso les recomiendo a que revisen y adopten el Modelo de Madurez de Datos ( Data Maturity Model DMM) que, al ser implementado, nos puede ayudar a todos ahorrar muchas frustraciones y costos.

Saludos Hanna Oktaba

Enviado desde mi iPhone
